version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    container_name: semt-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:4000

  backend:
    build:
      context: ./backend
    container_name: semt-backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/semt
      - JWT_SECRET=dev_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: semt-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
